# Generated by Django 3.1.6 on 2021-02-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator', models.TextField()),
                ('text', models.TextField()),
                ('is_harmful', models.BooleanField()),
                ('is_opinion', models.BooleanField()),
                ('is_fact', models.BooleanField()),
                ('extracted_span', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
