# Generated by Django 3.1.6 on 2021-02-17 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0003_auto_20210217_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluated_snippet',
            name='snippet',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.RESTRICT, related_name='evaluated_snippets', to='labeller.snippet'),
            preserve_default=False,
        ),
    ]
