# Generated by Django 3.1.6 on 2021-02-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeller', '0005_evaluated_snippet_is_spam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluated_snippet',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
